### ISSUE TITLE
Blocking mode?

### ISSUE THREAD

**Issue by cdleonard** [pdudaemon/pdudaemon#75]
All current pdudaemon operations are asynchronous and delayed (#72). It's possible that for client sequence of `off(); sleep(1); on();` pdudaemon delays will cause "off" to take effect after the on() call. This can be worked around (for example with longer sleep times) but it's nasty.

I think it would be reasonable to support a "block=true" parameter that makes "on/off" requests to only return after the driver does. This could also propagate driver errors back to the client.

**Comment by jluebbe** [comment]
The asynchronous behavior also makes it a bit problematic to use it via the [PDUDaemonDriver](https://labgrid.readthedocs.io/en/latest/configuration.html#pdudaemondriver) in labgrid, as we don't know when the power is actually switched.
I think that i heard last year's ATS, that this might be resolved by removing the database of queued request and handling each PDU via a asyncio task.

**Comment by mattface** [comment]
@jluebbe You could use the --drive mode which directly calls the driver and will not exit until the request is finished, however obviously that doesn't help with situations where a PDU can't handle concurrent connections.

Otherwise yes, blocking calls are a feature I've been asked about before, and it is on the to-do list, with asyncio probably being the right choice for dropping the database requirement and making blocking calls easier. I plan to look into this but I don't yet have a timescale.

**Comment by jluebbe** [comment]
This was solved with #78, closing.
